using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ssf.Generation
{
    public class NameGenerator
    {
        public static List<string> adj = new List<string>
        {
            "Forsaken",
            "Deserted",
            "Neglected",
            "Discarded",
            "Forgotten",
            "Abandoned",
            "Relinquished",
            "Vacant",
            "Desolate",
            "Unoccupied",
            "Derelict",
            "Despoiled",
            "Isolated",
            "Renounced",
            "Surrendered",
            "Disowned",
            "Disregarded",
            "Unclaimed",
            "Ignored",
            "Forsook",
            "Vacated",
            "Uninhabited",
            "Unprotected",
            "Destitute",
            "Dilapidated",
            "Ramshackle",
            "Decrepit",
            "Decayed",
            "Distant",
            "Faraway",
            "Secluded",
            "Outlying",
            "Inaccessible",
            "Far-flung",
            "Lonely",
            "Aloof",
            "Sequestered",
            "Outer",
            "Peripheral",
            "Rural",
            "Removed",
            "Solitary",
            "Unreachable",
            "Cut-off",
            "Shielded",
            "Protected",
            "Fortified",
            "Armoured",
            "Plated",
            "Ironclad",
            "Reinforced",
            "Secured",
            "Safeguarded",
            "Defended",
            "Covered",
            "Bulletproof",
            "Steel-clad",
            "Armored-up",
            "Encased",
            "Hardened",
            "Armor-plated",
            "Metal-clad",
            "Armored",
            "Combat-ready",
            "Unyielding"
        };

        public static List<string> noun = new List<string>
        {
            "Transit Point",
            "Holding Area",
            "Base",
            "Garrison",
            "Fort",
            "Camp",
            "Outpost",
            "Barracks",
            "Station",
            "Encampment",
            "Installation",
            "Stronghold",
            "Command Center",
            "Military Base",
            "Post",
            "Cantonment",
            "Headquarters",
            "Defense Post",
            "Army Post",
            "Operational Base",
            "Staging Area",
            "Military Installation",
            "Fortification",
            "Stronghold",
            "Military Base",
            "Outpost",
            "Station",
            "Encampment",
            "Armory",
            "Command Post",
            "Depot",
            "Military Post",
            "Cantonment",
            "Installation",
            "Quarters",
            "Military Station",
            "Defense Post",
            "Citadel",
            "Billet",
            "Bunker",
            "Fortress",
            "Compound",
            "Watchtower",
            "Barricade",
            "Hold",
            "Redoubt",
            "Bastion",
            "Defensive Line",
            "War camp",
            "Blockhouse",
            "Stockade",
            "Palisade",
            "Enclave",
            "Entrenchment",
            "Parapet",
            "Bulwark",
            "Guardhouse",
            "Enclosure",
            "Presidio",
            "Armament",
            "Fortlet",
            "Field Camp",
            "Barrage",
            "Sentry Post",
            "Fire Base",
            "Guard Post",
            "Military Encampment",
            "Siege Camp",
            "Command center",
            "Security Station",
            "Battle Station",
            "Trench",
            "War Station",
            "Defensive Position",
            "Combat Outpost",
            "Reinforced Position",
            "Quartier",
            "Redoute",
            "Keep",
            "Alcazar",
            "Battlement",
            "Armored Bastion"
        };


        public static string GetRandomPOIName(int seed)
        {
            string result = "";
            Random rand = new Random(seed);

            result = adj[rand.Next(adj.Count - 1)] + " " + noun[rand.Next(noun.Count - 1)];

            return result;
        }
    }
}
